#!/bin/bash
# Merchant Quest - Deploy Script
# This script helps you deploy to Vercel (frontend) and Render (backend)

echo "⚔️  Merchant Quest - Deploy Guide"
echo ""
echo "============================================"
echo "  PASO 1: Deploy Backend a Render (gratis)"
echo "============================================"
echo ""
echo "1. Ve a https://render.com y crea cuenta (gratis)"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Conecta tu repositorio GitHub: Fadosumalinux/merchant-quest"
echo "4. Configura:"
echo "   - Name: merchant-quest-api"
echo "   - Runtime: Node"
echo "   - Build Command: cd server && npm install && npx prisma generate && npx prisma db push && npx prisma db seed"
echo "   - Start Command: cd server && npx tsx src/index.ts"
echo "   - Environment Variables:"
echo "     DATABASE_URL = file:./prod.db"
echo "     JWT_SECRET = (click Generate)"
echo "     PORT = 3001"
echo "5. Click 'Create Web Service'"
echo "6. Espera 2-3 minutos y copia la URL (ej: https://merchant-quest-api.onrender.com)"
echo ""
echo "============================================"
echo "  PASO 2: Deploy Frontend a Vercel (gratis)"
echo "============================================"
echo ""
echo "1. Ve a https://vercel.com y crea cuenta (gratis)"
echo "2. Click 'Add New...' → 'Project'"
echo "3. Importa el repositorio: Fadosumalinux/merchant-quest"
echo "4. Configura:"
echo "   - Framework: Vite"
echo "   - Root Directory: client"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "   - Environment Variables:"
echo "     VITE_API_URL = https://merchant-quest-api.onrender.com/api"
echo "5. Click 'Deploy'"
echo "6. Espera 1-2 minutos y tendrás tu URL pública"
echo ""
echo "============================================"
echo "  ¡LISTO!"
echo "============================================"
echo ""
echo "Comparte la URL de Vercel con tu equipo."
echo "Todos podrán jugar sin necesidad de tu máquina encendida."
